# version: '3'

# services:
#   laravel-app:
#     build:
#       context: ./laravel-app
#       dockerfile: Dockerfile
#     image: laravel-app:latest
#     volumes:
#       - ./laravel-app:/var/www/html
#     ports:
#       - "8080:80"
#     environment:
#       - DB_CONNECTION=mysql
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_DATABASE=dbo_laravel
#       - DB_USERNAME=user
#       - DB_PASSWORD=password

#   react-app:
#     build:
#       context: ./my-app
#       dockerfile: Dockerfile
#     image: react-app:latest
#     ports:
#       - "3000:3000"
  
#   db:
#     image: mysql:5.7
#     volumes:
#       - db_data:/var/lib/mysql
#     environment:
#       - MYSQL_DATABASE=dbo_laravel
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=password
#       - MYSQL_ROOT_PASSWORD=root_password

# volumes:
#   db_data: {}

version: '3'

services:
  laravel-app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    image: laravel-app:latest
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=mysql
      - MYSQL_HOST=db 
      - DB_PORT=3306
      - DB_DATABASE=dbo_laravel
      - DB_USERNAME=user3
      - DB_PASSWORD=123123123
    depends_on:
      - db
  react-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    image: react-app:latest
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dbo_laravel
      - MYSQL_USER=user3
      - MYSQL_PASSWORD=123123123
      - MYSQL_ROOT_PASSWORD=123123123
      - MYSQL_ROOT_HOST=%
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  db_data: {}
  